CREATE TABLE [dbo].[RailTariff] (
    [RailRoad]         VARCHAR (80) NULL,
    [Price ID]         DECIMAL (18) NULL,
    [Location/Product] VARCHAR (80) NULL,
    [Locale]           VARCHAR (80) NULL,
    [Product]          VARCHAR (25) NULL,
    [Modified]         VARCHAR (25) NULL,
    [Currency/UOM]     VARCHAR (25) NULL,
    [From Date]        DATETIME     NULL,
    [To Date]          DATETIME     NULL,
    [Type]             VARCHAR (25) NULL,
    [Delivery Period]  VARCHAR (25) NULL,
    [Status]           VARCHAR (25) NULL,
    [Gravity Table]    VARCHAR (25) NULL,
    [Gravity]          VARCHAR (25) NULL,
    [Comment]          VARCHAR (25) NULL,
    [Error Message]    VARCHAR (25) NULL,
    [SingleStandardRR] VARCHAR (25) NULL,
    [SingleStandardSO] VARCHAR (25) NULL,
    [SingleHeavyRR]    VARCHAR (25) NULL,
    [SingleHeavySO]    VARCHAR (25) NULL,
    [TrainHeavyRR]     VARCHAR (25) NULL,
    [TrainHeavySO]     VARCHAR (25) NULL,
    [TrainStandardRR]  VARCHAR (25) NULL,
    [TrainStandardSO]  VARCHAR (25) NULL,
    [65HeavyRR]        VARCHAR (25) NULL,
    [65StandardRR]     VARCHAR (25) NULL,
    [65StandardSO]     VARCHAR (25) NULL,
    [SingleSteelSO]    VARCHAR (25) NULL,
    [65HeavySO]        VARCHAR (25) NULL,
    [25StandardRR]     VARCHAR (25) NULL,
    [50StandardRR]     VARCHAR (25) NULL,
    [75HeavyRR]        VARCHAR (25) NULL,
    [75StandardRR]     VARCHAR (25) NULL,
    [25HeavyRR]        VARCHAR (25) NULL,
    [50HeavyRR]        VARCHAR (25) NULL,
    [85StandardRR]     VARCHAR (25) NULL,
    [85HeavyRR]        VARCHAR (25) NULL,
    [110StandardRR]    VARCHAR (25) NULL,
    [110HeavyRR]       VARCHAR (25) NULL,
    [100HeavyRR]       VARCHAR (25) NULL,
    [100StandardRR]    VARCHAR (25) NULL,
    [FromLocation]     VARCHAR (50) NULL,
    [ToLocation]       VARCHAR (50) NULL
);

